config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'schools#index'

  get '/api/schools', to:'api#index'
  get '/api/school', to:'api#show'
  get '/api/cities', to:'api#cities'

  resources :schools do
    resources :teachers, except: [:edit]
    resources :courses, except: [:edit]
    resources :addresses, except: [:edit]
    resources :networks, except: [:edit]
  end
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id         :bigint           not null, primary key
#  bio        :text
#  email      :string
#  first_name :string
#  last_name  :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  school_id  :bigint
#
# Indexes
#
#  index_teachers_on_school_id  (school_id)
#
# Foreign Keys
#
#  fk_rails_...  (school_id => schools.id)
#
class Teacher < ApplicationRecord
  has_many :teachings, dependent: :destroy
  belongs_to :school
  has_one_attached :photo
  has_rich_text :bio

  validates_presence_of :first_name, message: "Veuillez préciser le nom de votre professeur"
  validates :email, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "L'email n'est pas valide"}
  # validates_format_of :phone, with: /\A(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}/, message: "Le numero de téléphone ne semble pas correct" 
  
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  
  before_action :set_teacher, except: [:index, :new, :create]

  def index
    @school = School.find(params[:school_id]) 
    @teachers = @school.teachers.order("last_name")
    add_breadcrumb("Mes profs")
  end
  
  def show
    @school = School.find(params[:school_id])
    add_breadcrumb("Mes profs", school_teachers_path(@school))
    add_breadcrumb(@teacher.first_name+' '+@teacher.last_name)
    add_breadcrumb("Modifier")
  end

  def new
    @school = School.find(params[:school_id])
    @teacher = @school.teachers.new
    authorize @teacher
    add_breadcrumb("Ajouter un prof")
  end
  
  def create
    @school = School.find(params[:school_id])
    @teacher = Teacher.new(teacher_params)
    @teacher.school = @school
    authorize @teacher
    if @teacher.save
      redirect_to school_teachers_path(@school)
    else
      render :new
    end
  end

  def update
    
    @school = School.find(params[:school_id])
    if @teacher.update(teacher_params)
      redirect_to school_teachers_path(@school)
    else
      render :show
    end
  end


  def destroy
    @school = School.find(params[:school_id])
    @teacher.destroy

    redirect_to school_teachers_path(@school)
  end

  private

  def teacher_params
    params.require(:teacher).permit( :email, :first_name, :last_name, :bio, :phone, :photo)
  end

  def set_teacher
    @teacher = Teacher.find(params[:id])
    authorize @teacher
  end

end

app/views/teachers/_deleteModal.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div x-show="open" id="deleteSchoolModal" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class=" flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <!--
      Background overlay, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

    <!--
      Modal panel, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
    <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
      <div class="sm:flex sm:items-start">
        <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
          <!-- Heroicon name: outline/exclamation -->
          <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        </div>
        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
          <h3 class="text-lg leading-6 text-center font-sm text-gray-900" id="modal-title">
            Confirmez-vous la suppression du prof <br> <strong> <%= @teacher.full_name %> </strong> ?
          </h3>
        </div>
      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse justify-around">
        <%= link_to "Supprimer le prof", "/schools/#{@school.id}/teachers/#{@teacher.id}", id: "delete_school" ,method: :delete, class: " bg-red-500 py-2 px-4 rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <button @click="open = false" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm">
          Annuler
        </button>
      </div>
    </div>
  </div>
</div>

app/views/teachers/_teacherForm.html.erb
<%= form_for([@school, @teacher]) do |teacher_form| %>

  <div class="space-y-8 divide-y divide-gray-200">

    <div>
      <div class="flex justify-between items-start">
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Informations sur <%= @teacher.first_name ? "#{@teacher.first_name} #{@teacher.last_name}" : "votre prof" %>
          </h3>
        </div>
        <div x-data="{photoName: null, photoPreview: null}" class="">
           <!-- Photo File Input -->
          <%= teacher_form.file_field :photo, "x-ref" => "photo", "x-on:change" => 
          "photoName = $refs.photo.files[0].name;
                        const reader = new FileReader();
                        reader.onload = (e) => {
                            photoPreview = e.target.result;
                        };
                        reader.readAsDataURL($refs.photo.files[0]);" ,class: "hidden"  %>
          <div class="text-center">
              <!-- Current Profile Photo -->
            <div class="" x-show="! photoPreview">
                <img src="<%= @teacher.photo.url || "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2015%2F10%2F05%2F22%2F37%2Fblank-profile-picture-973460_640.png&f=1&nofb=1" %>" class="h-16 w-16 lg:w-16 lg:h-16 md:w-10 md:h-10 m-auto rounded-full shadow">
            </div>
              <!-- New Profile Photo Preview -->
            <div class="" x-show="photoPreview" style="display: none;">
                <span class="block w-16 h-16 rounded-full m-auto shadow" x-bind:style="'background-size: cover; background-repeat: no-repeat; background-position: center center; background-image: url(\'' + photoPreview + '\');'" style="background-size: cover; background-repeat: no-repeat; background-position: center center; background-image: url('null');">
                </span>
            </div>
            <button type="button" class="inline-flex items-center px-2 py-1 md:px-1 bg-white border border-gray-300 rounded-md font-semibold text-xs text-gray-700 uppercase tracking-widest shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-400 focus:shadow-outline-blue active:text-gray-800 active:bg-gray-50 transition ease-in-out duration-150 mt-2" x-on:click.prevent="$refs.photo.click()">
                Changer la photo
            </button>
          </div>
        </div>
        
      </div>
      
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">

        <div class="sm:col-span-3">
          <label for="name" class="block text-sm font-medium text-gray-700">
            Prenom
          </label>
          <div class="mt-1">
            <%= teacher_form.text_field :first_name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "Prenom" %>
            <%= render  "shared/form_errors", locals: {item: @teacher ,property: :first_name} %>
          </div>
        </div>
        <div class="sm:col-span-3">
          <label for="name" class="block text-sm font-medium text-gray-700">
            Nom
          </label>
          <div class="mt-1">
            <%= teacher_form.text_field :last_name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "Nom" %>
            <%= render  "shared/form_errors", locals: {item: @teacher ,property: :last_name} %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="last_name" class="block text-sm font-medium text-gray-700">
            Email de contact (il ne sera visible que de vous)
          </label>
          <div class="mt-1">
            <%= teacher_form.text_field :email, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "email@gmail.com" %>
            <%= render  "shared/form_errors", locals: {item: @teacher ,property: :email} %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Téléphone (il ne sera visible que de vous)
          </label>
          <div class="mt-1">
            <%= teacher_form.text_field :phone, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "06 12 12 12 12" %>
            <%= render  "shared/form_errors", locals: {item: @teacher ,property: :phone} %>
          </div>
        </div>

        <div class="sm:col-span-6">
          <label for="email" class="block text-sm font-medium text-gray-700">
            <%= @teacher.first_name ? "#{@teacher.first_name} #{@teacher.last_name}" : "Description de votre prof" %> 
          </label>
          <p class="mt-1 text-sm text-gray-500">
            Donnez ici une description du parcours de <%= @teacher.first_name ? "#{@teacher.first_name} #{@teacher.last_name}" : "votre prof" %> mais aussi ce qui les caractéristiques des cours que ce professeur prodigue
          </p>
          <div class="mt-1 trix">
            <%= teacher_form.rich_text_area :bio %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pt-5">

    <div class="flex items-center">
      <% unless params[:action] == "new" || params[:action] == "create" %>
        <div x-data="{ open: false }">
          <a @click="open = true" style="cursor: pointer;" class="bg-red-500 py-2 px-4 rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="delete_school">Supprimer le prof</a> 
          <%= render  "deleteModal" %>
        </div>
      <% end %>
      <div class="flex justify-end ml-auto">
        <%= link_to "Annuler", school_teachers_path(@school), class: "bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <%= teacher_form.submit "Enregistrer", class: "ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%> 

      </div>
    </div>
  </div>
<% end %>

app/views/teachers/index.html.erb
<main class=" bg-red flex-1 relative overflow-y-auto focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">


      <p class="mt-1 text-sm text-gray-500">
        Tous les professeurs de votre école <%= @school.name %>           
      </p>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <!-- This example requires Tailwind CSS v2.0+ -->
      <ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        <% @teachers.each do |teacher|   %>
            <li class="col-span-1 bg-white relative rounded-lg shadow divide-y divide-gray-200 truncate">
              <div class="w-full flex items-center justify-between p-6 space-x-4">
              <%= link_to school_teacher_path(@school, teacher) do %>
                <div class="flex-1">
                  <%=cl_image_tag teacher.photo.key, crop: :crop, gravity: :face, class: "flex-shrink-0 inline-block absolute top-2 right-5 inline-block h-10 w-10 rounded-full" %>
                  <div class=" items-center space-x-3">
                    <h3 class="text-gray-900 mt-4  text-sm font-medium truncate"><%= teacher.first_name %> <%= teacher.last_name %></h3>
                  </div>
                  
                </div>

              <% end %>
              </div>
              <div>
                <div class="-mt-px flex divide-x divide-gray-200">
                  <div class="w-0 flex-1 flex">
                    <%= link_to school_teacher_path(@school, teacher), class: "relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                      <span class="ml-3">Modifier</span>
                    <% end  %> 
                  </div>

                </div>
              </div>
            </li>
        <% end %>


        <li class="col-span-1 rounded-lg shadow divide-y divide-gray-200">
          <%= link_to new_school_teacher_path(@school) do  %>
          <div class="w-full flex items-center justify-between p-6 space-x-4">
            <div class="flex-1 truncate">
              <div class="flex items-center space-x-3">
                <h3 class="text-gray-900 text-sm font-medium truncate items-center">Ajouter un nouveau prof</h3>
              </div>
              <div>
          </div>
          <% end %>
        </li>

        <!-- More people... -->
      </ul>


    </div>
  </div>
</main>

app/views/teachers/new.html.erb
<main class="flex-1 relative overflow-y-auto bg-gray-100 focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8"></div>
     <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pb-3">
            <%= render 'teacherForm' %>
    </div>
  </div>
</main>

app/views/teachers/show.html.erb
<main class="flex-1 relative overflow-y-auto bg-gray-100 focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8"></div>
     <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 pb-3">
            <%= render 'teacherForm' %>
    </div>
  </div>
</main>