config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'schools#index'

  get '/api/schools', to:'api#index'
  get '/api/school', to:'api#show'
  get '/api/cities', to:'api#cities'

  resources :schools do
    resources :teachers, except: [:edit]
    resources :courses, except: [:edit]
    resources :addresses, except: [:edit]
    resources :networks, except: [:edit]
  end
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  before_action :set_schools
  before_action :set_school, except: [ :new]
  before_action :set_address, except: [:index, :new, :create]

  def index
    @addresses = @school.addresses.order(published: :desc)
    add_breadcrumb("Mes lieux de cours")
  end

  def show
    add_breadcrumb("Mes lieux de cours", school_addresses_path(@school))
    add_breadcrumb(@address.address)
    add_breadcrumb("Modifier")
  end

  def edit
    
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(address_params)
      redirect_to school_addresses_path(@school)
    else
      render :edit
    end
  end

  def new
    @school = School.find(params[:school_id])
    @address = @school.addresses.new
    authorize @address
    add_breadcrumb("Mes lieux de cours", school_addresses_path(@school))
    add_breadcrumb("Ajouter un lieu")
  end

  def create
    @address = Address.new(address_params)
    @address.school = @school
    authorize @address
    if @address.save
      redirect_to school_addresses_path(@school)
    else
      render :new
    end
  end

  def destroy
    @address.destroy
    redirect_to school_addresses_path(@school)
  end

  private

  def address_params
    params.require(:address).permit(:published, :address_complement,:address, :city, :zipcode, :phone, :details)
  end

  def set_address
    @address = Address.find(params[:id])
    authorize @address
  end

  def set_schools
    @schools =  policy_scope(School).where(user: current_user)
  end

  def set_school
    @school = policy_scope(School).find(params[:school_id])
  end
  
end

app/views/addresses/_addressForm.html.erb
<%= form_for([@school, @address]) do |address_form| %>
  <div class="space-y-8 divide-y divide-gray-200">

    <div>
      <div class="flex justify-between sm:flex-col md:flex-row">
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Informations sur votre adresse <%= @address.address unless !@address.address %>
          </h3>
        </div>
        <div class="flex sm:mt-4 md:mt-0">

          <label for="first_name"  class="mb-3 block text-md font-medium text-gray-700">
              <span id="publishLabel" class="ease-out duration-500 flex-shrink-0 inline-block px-2 py-0.5 text-sm font-medium <%= @address.published ? "bg-green-200  text-green-800" : "bg-red-300  text-red-800" %> rounded-full"> <%= @address.published ? "Publié" : "Non publié" %></span>
          </label>
          
          <button x-on:click="toggle === '1' ? $refs.publish.value = false : $refs.publish.value = true"
                  :class="[toggle === '1' ? 'bg-indigo-400' : 'bg-gray-200']" 
                  @click="toggle === '0' ? toggle = '1' : toggle = '0'" 
                  type="button" id="btnTogglePublish"
                  x-data="{ toggle: '<%=@address.published ? '1' : '0' %>' }"  class=" relative ml-2 inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none" role="switch" aria-checked="false">
            
            <%= address_form.hidden_field :published, "x-ref"=> "publish"%>
            <span class="sr-only">Use setting</span>
            <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
            <span  :style="[toggle === '1' ? 'transform: translateX(20px);' : 'transform: translateX(0px);']"  :class="[toggle === '1' ? 'translate-x-5' : 'translate-x-0']" class="pointer-events-none relative inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200">
              <!-- Enabled: "opacity-0 ease-out duration-100", Not Enabled: "opacity-100 ease-in duration-200" -->
              <span :class="[toggle === '1' ? 'opacity-0 ease-out duration-100' : 'opacity-100 ease-in duration-200']" class="absolute inset-0 h-full w-full flex items-center justify-center transition-opacity" aria-hidden="true">
                <svg class="h-3 w-3 text-gray-400" fill="none" viewBox="0 0 12 12">
                  <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
              </span>
              <!-- Enabled: "opacity-100 ease-in duration-200", Not Enabled: "opacity-0 ease-out duration-100" -->
              <span  :class="[toggle === '1' ? 'opacity-100 ease-in duration-200' : 'opacity-0 ease-out duration-100']" class=" absolute inset-0 h-full w-full flex items-center justify-center transition-opacity" aria-hidden="true">
                <svg class="h-3 w-3 text-indigo-600" fill="currentColor" viewBox="0 0 12 12">
                  <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z" />
                </svg>
              </span>
            </span>
          </button>
        </div>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label for="first_name" class="block text-sm font-medium text-gray-700">
            Adresse
          </label>
          <div class="mt-1">
            <%= address_form.text_field :address, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "12 avenue Charles De gaulle" %>
            <%= render  "shared/form_errors", locals: {item: @address ,property: :address} %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="last_name" class="block text-sm font-medium text-gray-700">
            Complément d'adresse
          </label>
          <div class="mt-1">
            <%= address_form.text_field :address_complement, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "Batiment B2" %>

          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Ville
          </label>
          <div class="mt-1">
            <%= address_form.text_field :city, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "Marseille" %>
            <%= render  "shared/form_errors", locals: {item: @address ,property: :city} %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Code postal
          </label>
          <div class="mt-1">
            <%= address_form.text_field :zipcode, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "13008" %>
            <%= render  "shared/form_errors", locals: {item: @address ,property: :zipcode} %>

          </div>
        </div>
        
        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Télephone
          </label>
          <div class="mt-1">
            <%= address_form.text_field :phone, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "06 12 12 12 12" %>
            <%= render  "shared/form_errors", locals: {item: @address ,property: :phone} %>
          </div>
        </div>
          

        <div class="sm:col-span-6 ">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Détails de l'addresse votre école.
          </label>
          <div class="mt-1">
            <%= address_form.rich_text_area :details %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="flex items-center">
    <% unless params[:action] == "new" || params[:action] == "create" %>
      <div x-data="{ open: false }">
        <a @click="open = true" style="cursor: pointer;" class="bg-red-500 py-2 px-4 rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="delete_school">Supprimer l'adresse</a> 
        <%= render  "deleteModal" %>
      </div>
    <% end %>
      <div class="flex justify-end ml-auto">
        <%= link_to "Annuler", school_addresses_path(@school), class: " bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <%= address_form.submit "Enregistrer", class: " justify-flex-end ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    </div>

  </div>
<% end %>

app/views/addresses/_deleteModal.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div x-show="open" id="deleteSchoolModal" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <!--
      Background overlay, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

    <!--
      Modal panel, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
    <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
      <div class="sm:flex sm:items-start">
        <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
          <!-- Heroicon name: outline/exclamation -->
          <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        </div>
        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
          <h3 class="text-lg leading-6 text-center font-sm text-gray-900" id="modal-title">
            Confirmez-vous la suppression de l'adresse <br> <strong> <%= @address.address %> </strong> ?
          </h3>
        </div>
      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse justify-around">
        <%= link_to "Supprimer l'addresse", "/schools/#{@school.id}/addresses/#{@address.id}", id: "delete_school" ,method: :delete, class: " bg-red-500 py-2 px-4 rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <button @click="open = false" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm">
          Annuler
        </button>
      </div>
    </div>
  </div>
</div>

app/views/addresses/index.html.erb
<main class=" bg-red flex-1 relative overflow-y-auto focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">


      <p class="mt-1 text-sm text-gray-500">
        Toute les adresses de votre école <%= @school.name %>           
      </p>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <!-- This example requires Tailwind CSS v2.0+ -->
      <ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        <% @addresses.each do |address|   %>
            <li class="col-span-1 bg-white relative rounded-lg shadow divide-y divide-gray-200 truncate">
              <div class="w-full flex items-center justify-between p-6 space-x-4">
              <%= link_to school_address_path(@school, address) do %>
                <div class="flex-1">
                <span class="flex-shrink-0 inline-block absolute top-2 right-5 px-2 py-0.5 text-xs font-medium <%= address.published ? "bg-green-100  text-green-800" : "bg-red-300  text-red-800" %> rounded-full"> <%= address.published ? "Publié" : "Non publié" %></span>
                  <div class=" items-center space-x-3">
                    <h3 class="text-gray-900 mt-4  text-sm font-medium truncate"><%= address.address %></h3>
                  </div>
                <p class="mt-1 text-gray-500 text-sm truncate"><%= address.zipcode%> <strong><%= address.city  %></strong> </p>
                </div>
              <% end %>
              </div>
              <div>
                <div class="-mt-px flex divide-x divide-gray-200">
                  <div class="w-0 flex-1 flex">
                    <%= link_to school_address_path(@school, address), class: "relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500" do %>
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                      </svg>
                      <span class="ml-3">Modifier</span>
                    <% end  %> 
                  </div>

                </div>
              </div>
            </li>
        <% end %>


        <li class="col-span-1 rounded-lg shadow divide-y divide-gray-200">
          <%= link_to new_school_address_path(@school) do  %>
          <div class="w-full flex items-center justify-between p-6 space-x-4">
            <div class="flex-1 truncate">
              <div class="flex items-center space-x-3">
                <h3 class="text-gray-900 text-sm font-medium truncate items-center">Ajouter un nouveau lieu de cours</h3>

              </div>
              <div>
          </div>
          <% end %>
        </li>

        <!-- More people... -->
      </ul>


    </div>
  </div>
</main>

app/views/addresses/new.html.erb
<main class="flex-1 relative overflow-y-auto bg-gray-100 focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8"></div>
     <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <%= render 'addressForm' %>
    </div>
  </div>
</main>

app/views/addresses/show.html.erb
<main class="flex-1 relative overflow-y-auto bg-gray-100 focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8"></div>
     <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <%= render 'addressForm' %>
    </div>

  </div>
</main>