config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'schools#index'

  get '/api/schools', to:'api#index'
  get '/api/school', to:'api#show'
  get '/api/cities', to:'api#cities'

  resources :schools do
    resources :teachers, except: [:edit]
    resources :courses, except: [:edit]
    resources :addresses, except: [:edit]
    resources :networks, except: [:edit]
  end
  post "/upload_image" => "upload#upload_image", :as => :upload_image
  get "/download_file/:name" => "upload#access_file", :as => :upload_access_file, :name => /.*/
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id                 :bigint           not null, primary key
#  blog_default       :text
#  blog_default_days  :string
#  blog_order         :integer          default(0)
#  city               :string
#  description        :text
#  email              :string
#  imparato_blog_link :string
#  name               :string
#  published          :boolean
#  website            :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :bigint           not null
#
# Indexes
#
#  index_schools_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class School < ApplicationRecord
  belongs_to :user
  has_many :networks, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :teachers, dependent: :destroy
  has_many :courses, through: :addresses
  has_rich_text :description

  accepts_nested_attributes_for :networks
  
  validates_presence_of :name, message: "Veuillez entrer un nom à votre école"
  validates_presence_of :city, message: "Veuillez préciser la ville votre école"
  validates :email, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "L'email n'est pas valide"}

  validates_uniqueness_of :name, scope: [:city], message: "Cette école existe déjà"
  # validates_uniqueness_of :blog_order, scope: [:city]
  before_validation :check_order
  before_save :update_blog_order
  # before_create :update_blog_order
  # School.where(city: "Paris").last.blog_order + 1
  # last update of school and associated entities
  def last_update
    request = <<-STRING
                SELECT max(updated_at) FROM
                (SELECT updated_at FROM schools WHERE id = #{id}
                UNION
                SELECT updated_at FROM teachers WHERE school_id = #{id}
                UNION
                SELECT updated_at FROM addresses WHERE school_id = #{id}
                UNION
                SELECT c.updated_at FROM courses c, addresses a WHERE a.school_id = #{id} AND c.address_id = a.id
                UNION
                SELECT p.updated_at FROM properties p, courses c, addresses a WHERE a.school_id = #{id} AND c.address_id = a.id AND p.course_id = c.id) as subquery
    STRING
    return ActiveRecord::Base.connection.execute(request).first["max"]
  end

  # last update of a city name (get the max last update form all school and asociated entities)
  def self.last_udpate_city(city)
    request = <<-STRING
                SELECT max(updated_at) FROM
                (SELECT updated_at FROM schools WHERE city = '#{city}'
                UNION
                SELECT t.updated_at FROM teachers t, schools s WHERE t.school_id = s.id AND s.city = '#{city}'
                UNION
                SELECT a.updated_at FROM addresses a, schools s WHERE a.school_id = s.id AND s.city = '#{city}'
                UNION
                SELECT c.updated_at FROM courses c, addresses a, schools s WHERE a.school_id = s.id AND s.city = '#{city}' AND c.address_id = a.id
                UNION
                SELECT p.updated_at FROM properties p, courses c, addresses a, schools s WHERE a.school_id = s.id AND s.city = '#{city}' AND c.address_id = a.id AND p.course_id = c.id) as subquery
    STRING
    return ActiveRecord::Base.connection.execute(request).first["max"]
  end

  # gives cities names that are not in main_cities
  def self.secondary_cities
    request_other_cities = "SELECT distinct s.city FROM schools s LEFT JOIN main_cities mc ON mc.city = s.city WHERE mc.id IS NULL ORDER BY city ASC"
    other_cities = ActiveRecord::Base.connection.execute(request_other_cities)
  end

  private

  def check_order
    # renumbering cascade if collision
    if will_save_change_to_blog_order?
      to_move = School.where(city: city, blog_order: blog_order).first
      to_move&.update!(blog_order: to_move.blog_order + 1)
    end
  end

  def update_blog_order
    if !School.where(city: city).last.nil?
      order = School.where(city: city).last.blog_order 
      self.blog_order = order + 1
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  
  before_action :set_school, except: [:index, :new, :create]

  def index
    
  end

  def show 
    networks_count = 4 - @school.networks.count
    networks_count.times {@school.networks.build}
    add_breadcrumb("Modifier")
  end

  def new
    @school = current_user.schools.new
    authorize @school
    @school.networks.build
  end
  
  def create
    @school = School.new(schools_params)
    @school.user = current_user
    authorize @school
    if @school.save
      redirect_to schools_path, notice: "Création de l'école reussie"
    else
      render "new"
    end
  end
  
  def update
    params["school"]["networks_attributes"].permit! 
    if @school.update(schools_params)
      params["school"]["networks_attributes"].each do |network|
        if Network.find_by(url: network[1]["url"], school: @school).nil?
          if !network[1]["id"] 
            net = Network.create( url: network[1]["url"], school: @school )
          else
            net = Network.find(network[1]["id"])
            net.update(url: network[1]["url"])
          end
        end
      end
      # raise
      redirect_to schools_path, notice: "Modification de l'école reussie"
    else
      render :show
    end
  end

  def destroy
    authorize @school
    @school.destroy
    redirect_to schools_path, notice: "Suppression de l'école reussie"
  end

  private

  def set_school
    @school = School.find(params[:id])
    authorize @school
  end

  def schools_params
    params.require(:school).permit(:name, :published, :description, :email, :address_id ,:website, :city, networks: [])
  end

end

app/views/schools/_deleteModal.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div x-show="open" id="deleteSchoolModal" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <!--
      Background overlay, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <!-- This element is to trick the browser into centering the modal contents. -->
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

    <!--
      Modal panel, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        To: "opacity-100 translate-y-0 sm:scale-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100 translate-y-0 sm:scale-100"
        To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
    -->
    <div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
      <div class="sm:flex sm:items-start">
        <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
          <!-- Heroicon name: outline/exclamation -->
          <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
        </div>
        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
          <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
            Confirmez-vous la suppression de l'école <%= @school.name %> ?
          </h3>
          <div class="mt-2">
            <p class="text-sm text-gray-500">
             Attention, la suppression d'une école entraine aussi la <strong>suppression</strong> de toutes ses <strong>adresses</strong>, des <strong>professeurs</strong> et des <strong>cours</strong> déjà déclarés. Pour que l'école ne soit plus visible, vous pouvez aussi simplement la <strong>dépublier.</strong>
            </p>
          </div>
        </div>
      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
        <%= link_to "Supprimer l'école", "/schools/#{@school.id}" ,method: :delete, class: " bg-red-500 py-2 px-4 rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <button @click="open = false" type="button" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm">
          Annuler
        </button>
      </div>
    </div>
  </div>
</div>

app/views/schools/_network_fields.html.erb
<div class="flex -space-x-px">
  <div class="w-1/2 flex-1 min-w-0">
    <%= f.text_field :url, placeholder: "https://twitter.com/", class: "bg-white focus:ring-indigo-500 focus:border-indigo-500 relative block w-full rounded-none rounded-bl-md bg-transparent focus:z-10 sm:text-sm border-gray-300" %>
  </div>
</div>

app/views/schools/_schoolForm.html.erb
<%= form_for @school do |school_form| %>
  <div class="space-y-8 divide-y divide-gray-200">

    <div>
      <div class="flex justify-between sm:flex-col md:flex-row">
        <div>
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Informations sur votre école de théâtre amateur
          </h3>
        </div>


        <div class="flex sm:mt-4 md:mt-0">

          <label for="first_name"  class="mb-3 block text-md font-medium text-gray-700">
              <span id="publishLabel" class="ease-out duration-500 flex-shrink-0 h-6 inline-block px-2 py-0.5 text-sm font-medium <%= @school.published ? "bg-green-200  text-green-800" : "bg-red-300  text-red-800" %> rounded-full"> <%= @school.published ? "Publié" : "Non publié" %></span>
          </label>
          
          <button x-on:click="toggle === '1' ? $refs.publish.value = false : $refs.publish.value = true"
                  :class="[toggle === '1' ? 'bg-indigo-400' : 'bg-gray-200']" 
                  @click="toggle === '0' ? toggle = '1' : toggle = '0'" 
                  type="button" id="btnTogglePublish"
                  x-data="{ toggle: '<%=@school.published ? '1' : '0' %>' }"  class=" relative ml-2 inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none" role="switch" aria-checked="false">
            
            <%= school_form.hidden_field :published, "x-ref"=> "publish"%>
            <span class="sr-only">Use setting</span>
            <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
            <span :style="[toggle === '1' ? 'transform: translateX(20px);' : 'transform: translateX(0px);']" :class="[toggle === '1' ? 'translate-x-5' : 'translate-x-0']" class="pointer-events-none relative inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200">
              <!-- Enabled: "opacity-0 ease-out duration-100", Not Enabled: "opacity-100 ease-in duration-200" -->
              <span class="absolute inset-0 h-full w-full flex items-center justify-center transition-opacity" aria-hidden="true">
                <svg class="h-3 w-3 text-gray-400" fill="none" viewBox="0 0 12 12">
                  <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
              </span>
              <!-- Enabled: "opacity-100 ease-in duration-200", Not Enabled: "opacity-0 ease-out duration-100" -->
              <span  :class="[toggle === '1' ? 'opacity-100 ease-in duration-200' : 'opacity-0 ease-out duration-100']" class=" absolute inset-0 h-full w-full flex items-center justify-center transition-opacity" aria-hidden="true">
                <svg class="h-3 w-3 text-indigo-600" fill="currentColor" viewBox="0 0 12 12">
                  <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z" />
                </svg>
              </span>
            </span>
          </button>
        </div>

      </div>
      <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label for="first_name" class="block text-sm font-medium text-gray-700">
            Nom
          </label>
          <div class="mt-1">
            <%= school_form.text_field :name, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "L'atelier des Didascalies, Les Cours de Jean-Baptiste etc etc ... " %>
            <%= render  "shared/form_errors", locals: {item: @school ,property: :name} %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="last_name" class="block text-sm font-medium text-gray-700">
            Commune de l'école
          </label>
          <div class="mt-1">
            <%= school_form.text_field :city, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "Commune" %>
            <%= render  "shared/form_errors", locals: {item: @school ,property: :city} %>

          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Site web de l'école
          </label>
          <div class="mt-1">
            <%= school_form.text_field :website, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "https://mon-atelier-theatre.com" %>

          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Email de contact
          </label>
          <div class="mt-1">
            <%= school_form.text_field :email, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md p-3 py-2" ,placeholder: "https://mon-atelier-theatre.com" %>
            <%= render  "shared/form_errors", locals: {item: @school ,property: :email} %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Réseaux sociaux
          </label>
          <div class="col-span-3 mt-1 rounded-md shadow-sm bg-white -space-y-px">
        <% @school.networks.each do |network| %>
          <%= school_form.fields_for :networks, network do |network_form| %>
            <div class="flex -space-x-px">
              <div class="w-1/2 flex-1 min-w-0">
                <% if network == @school.networks[0] %>
                  <%= network_form.text_field :url, placeholder: "https://twitter.com/", class: "bg-white focus:ring-indigo-500 focus:border-indigo-500 relative block w-full rounded-none rounded-bl-md bg-transparent focus:z-10 sm:text-sm border-gray-300" %>
                <% elsif network == @school.networks[1] %>
                  <%= network_form.text_field :url, placeholder: "https://facebook.com/", class: "bg-white focus:ring-indigo-500 focus:border-indigo-500 relative block w-full rounded-none rounded-bl-md bg-transparent focus:z-10 sm:text-sm border-gray-300" %>
                <% elsif network == @school.networks[2] %>
                  <%= network_form.text_field :url, placeholder: "https://youtube.com/", class: "bg-white focus:ring-indigo-500 focus:border-indigo-500 relative block w-full rounded-none rounded-bl-md bg-transparent focus:z-10 sm:text-sm border-gray-300" %>
                <% else network == @school.networks[3] %>
                  <%= network_form.text_field :url, placeholder: "https://instagram.com/", class: "bg-white focus:ring-indigo-500 focus:border-indigo-500 relative block w-full rounded-none rounded-bl-md bg-transparent focus:z-10 sm:text-sm border-gray-300" %>
                <% end %>  
              </div>
            </div> 
          <% end %>
        <% end %>

          </div>
        </div>

        <div class="sm:col-span-6 ">
          <label for="email" class="block text-sm font-medium text-gray-700">
            Description de votre école.
          </label>
          <p class="mt-1 text-sm text-gray-500">
            Donnez ici une description générale de votre école. La description détaillée des cours se trouve dans l'onglet des cours.
          </p>
          <div class="mt-1">
            <%= school_form.rich_text_area :description %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pt-5">
    <div class="flex items-center">
    <% unless params[:action] == "new" || params[:action] == "create" %>
      <div x-data="{ open: false }">
        <a @click="open = true" style="cursor: pointer;" class="bg-red-500 py-2 px-4 rounded-md shadow-sm text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="delete_school">Supprimer l'école</a> 
        <%= render  "deleteModal" %>
      </div>
    <% end %>
      <div class="flex justify-end ml-auto">
        <%= link_to "Annuler", schools_path, class: " bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <%= school_form.submit "Enregistrer", style: "cursor: pointer;" ,class: " justify-flex-end ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    </div>

  </div>
<% end %>

app/views/schools/index.html.erb
      <main class=" bg-red flex-1 relative overflow-y-auto focus:outline-none">
        <div class="py-6">
          <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">


            <p class="mt-1 text-sm text-gray-500">
                Les écoles de théâtre que vous gèrez            
            </p>
          </div>

          <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <!-- This example requires Tailwind CSS v2.0+ -->
<ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-2">
  <% @schools.each do |school|   %>
      <li class="col-span-1 bg-white relative rounded-lg shadow divide-y divide-gray-200 truncate">
        <div class="w-full flex items-center justify-between p-6 space-x-4">
        <%= link_to school_path(school) do %>
          <div class="flex-1">
            <span class="flex-shrink-0 inline-block absolute top-2 right-5 px-2 py-0.5 text-xs font-medium <%= school.published ? "bg-green-100  text-green-800" : "bg-red-300  text-red-800" %> rounded-full"> <%= school.published ? "Publié" : "Non publié" %></span>
            <div class=" items-center space-x-3">
              <h3 class="text-gray-900 mt-4  text-sm font-medium truncate"><%= school.name %></h3>
            </div>
            <p class="mt-1 text-gray-500 text-sm truncate"><%= school.website %></p>
          </div>
        <% end %>
        </div>
        <div>
          <div class="-mt-px flex divide-x divide-gray-200">
            <div class="w-0 flex-1 flex">
              <%= link_to school_path(school), class: "relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-4 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-gray-500" do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                </svg>
                <span class="ml-3">Modifier</span>
              <% end  %> 
            </div>

          </div>
        </div>
      </li>
  <% end %>


  <li class="col-span-1 rounded-lg shadow divide-y divide-gray-200">
    <%= link_to new_school_path do  %>
    <div class="w-full flex items-center justify-between p-6 space-x-4">
      <div class="flex-1 truncate">
        <div class="flex items-center space-x-3">
          <h3 class="text-gray-900 text-sm font-medium truncate items-center">Ajouter une nouvelle école</h3>

        </div>
        <div>
    </div>
    <% end %>
  </li>

  <!-- More people... -->
</ul>


          </div>
        </div>
      </main>

app/views/schools/new.html.erb
<main class="flex-1 relative overflow-y-auto bg-gray-100 focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8"></div>
     <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <%= render 'schoolForm' %>
    </div>
  </div>
</main>

app/views/schools/show.html.erb
<main class="flex-1 relative overflow-y-auto bg-gray-100 focus:outline-none">
  <div class="py-6">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8"></div>
     <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-3">
            <%= render 'schoolForm' %>
    </div>

  </div>
</main>